// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/10/2025, 3:30:30 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Nikita/Desktop/suvlavka/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/suvlavka/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/suvlavka/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/suvlavka/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/suvlavka/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Nikita/Desktop/suvlavka/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Nikita/Desktop/suvlavka/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Nikita/Desktop/suvlavka/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/suvlavka/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/suvlavka/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/suvlavka/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;